"""Vendored stack-frame noise-ignore lists from ClusterFuzz and CASR.

**Status: prepared but NOT yet wired into `autofte/dedup.py`.** This module only
assembles the vendored data and a self-contained matcher on top of it; `dedup.py`'s
`_NOISE_FUNC_RE` / `is_noise_frame` are untouched and still drive real bucketing.
Swapping the live denylist over to this module is a separate, later task, gated on
`autofte bench` existing so the before/after effect on inverse purity can be
measured -- see `planning/HARDENING.md` Part 3's "land one at a time, measure"
discipline and `planning/research/05-accuracy-and-ground-truth.md` SS3.6.

Sources (both Apache-2.0; full license text at
https://www.apache.org/licenses/LICENSE-2.0):

- ClusterFuzz, `src/clusterfuzz/stacktraces/constants.py`
  (Copyright 2020 Google LLC), fetched live from
  https://raw.githubusercontent.com/google/clusterfuzz/master/src/clusterfuzz/stacktraces/constants.py
  on 2026-08-07. `STACK_FRAME_IGNORE_REGEXES` (210 entries, verbatim) is reproduced
  below as `CLUSTERFUZZ_FUNCTION_IGNORE_REGEXES`; `STACK_FRAME_IGNORE_REGEXES_IF_SYMBOLIZED`
  (5 entries, verbatim) as `CLUSTERFUZZ_FUNCTION_IGNORE_REGEXES_IF_SYMBOLIZED`.
- CASR / libcasr, `libcasr/src/constants.rs`
  (Copyright 2020 Google LLC, Modifications copyright (C) 2023 ISP RAS), fetched
  live from
  https://raw.githubusercontent.com/ispras/casr/master/libcasr/src/constants.rs
  on 2026-08-07. `STACK_FRAME_FUNCTION_IGNORE_REGEXES_CPP` (156 entries, verbatim --
  CASR ships 157 string literals in this list but one, `r"^main",`, is commented out
  in their source with `//`, so it is correctly excluded here too) is reproduced
  below as `CASR_CPP_FUNCTION_IGNORE_REGEXES`; `STACK_FRAME_FILEPATH_IGNORE_REGEXES_CPP`
  (43 entries, verbatim) as `CASR_CPP_FILEPATH_IGNORE_REGEXES`. This is CASR's C++
  list specifically -- CASR also ships separate Java/JS/Lua/Python/Rust/Go/C# lists
  not relevant to AutoFTE's ASan/UBSan C/C++ target scope.

Both files were fetched over the network from this sandbox and used verbatim, not
reconstructed from training-data memory -- so the counts above are exact, not
estimates. (`planning/HARDENING.md` Part 3 fix #2 cites ClusterFuzz's list as
"~180 patterns" from memory/prior research; the real file has 210. CASR's real C++
function list has 156, not the "~180" figure sometimes attributed to it either --
that estimate conflated it with ClusterFuzz's count. Both real counts are recorded
here so nobody downstream re-guesses.)

`EXTRA_FUNCTION_IGNORE_REGEXES` below adds the four patterns named explicitly in
research/05 SS3.6/SS3.7 that a term-by-term check found genuinely absent from both
ported lists above (not already covered by a broader prefix already present, e.g.
`^__GI_raise` is skipped because `^__GI_` already matches it): `^_Unwind_`,
`^std::__1?::`, `^__pthread_`, `^clone$`. The other names research/05 lists
(`^abort$`, `^raise$`, `^__GI_raise`, `^__GI_abort`, `^gsignal$`, `^malloc$`,
`^free$`, `^calloc$`, `^realloc$`, `^operator new`, `^operator delete`,
`^__cxa_throw`, `^fuzzer::`, `^LLVMFuzzerTestOneInput$`) are already matched by an
entry or a broader prefix already present in the ClusterFuzz/CASR lists above.

Matching semantics mirror how both source projects actually wrote these patterns:
`re.match` (anchored at position 0), with `.*`-prefixed entries used by the source
authors themselves wherever "contains anywhere" was the intent -- so this module
does the same rather than switching to `re.search`, which would change behavior
for the handful of entries that rely on the anchor (e.g. `^<unknown>$`).
"""

import re

CLUSTERFUZZ_FUNCTION_IGNORE_REGEXES = (
    '^abort$',
    '^exit$',
    '^pthread_create$',
    '^pthread_kill$',
    '^raise$',
    '^tgkill$',
    '^__chk_fail$',
    '^__fortify_fail$',
    '^(|__)aeabi_',
    '^(|__)memcmp',
    '^(|__)memcpy',
    '^(|__)memmove',
    '^(|__)memset',
    '^(|__)strcmp',
    '^(|__)strcpy',
    '^(|__)strdup',
    '^(|__)strlen',
    '^(|__)strncpy',
    '^<null>',
    '^Abort\\(',
    '^CFCrash',
    '^ExitCallback',
    '^IsSandboxedProcess',
    '^LLVMFuzzerTestOneInput',
    '^MSanAtExitWrapper',
    '^New',
    '^RaiseException',
    '^SbSystemBreakIntoDebugger',
    '^SignalAction',
    '^SignalHandler',
    '^TestOneProtoInput',
    '^WTF::',
    '^WTFCrash',
    '^X11Error',
    '^_L_unlock_',
    '^_\\$LT\\$',
    '^__GI_',
    '^___interceptor_backtrace',
    '^__asan::',
    '^__asan_',
    '^__assert_',
    '^__cxa_atexit',
    '^__cxa_rethrow',
    '^__cxa_throw',
    '^__dump_stack',
    '^__hwasan::',
    '^__hwasan_',
    '^__interceptor_',
    '^__kasan_',
    '^__libc_',
    '^__lsan::',
    '^__lsan_',
    '^__msan::',
    '^__msan_',
    '^__pthread_kill',
    '^__run_exit_handlers',
    '^__rust_try',
    '^__sanitizer::',
    '^__sanitizer_',
    '^__tsan::',
    '^__tsan_',
    '^__ubsan::',
    '^__ubsan_',
    '^_asan_',
    '^_hwasan_',
    '^_lsan_',
    '^_msan_',
    '^_objc_terminate',
    '^_sanitizer_',
    '^_start',
    '^_tsan_',
    '^_ubsan_',
    '^abort',
    '^alloc::',
    '^android\\.app\\.ActivityManagerProxy\\.',
    '^android\\.os\\.Parcel\\.',
    '^art::Thread::CreateNativeThread',
    '^asan_',
    '^asan\\.module_ctor',
    '^asan\\.module_dtor',
    '^calloc',
    '^check_memory_region',
    '^common_exit',
    '^core::fmt::write',
    '^delete',
    '^demangling_terminate_handler',
    '^dump_backtrace',
    '^dump_stack',
    '^exit_or_terminate_process',
    '^fpehandler\\(',
    '^free',
    '^fuzzer::',
    '^g_log',
    '^generic_cpp_',
    '^gsignal',
    '^kasan_',
    '^libfuzzer_sys::initialize',
    '^main',
    '^malloc',
    '^mozalloc_',
    '^new',
    '^object_err',
    '^operator',
    '^panic_abort::',
    '^print_trailer',
    '^realloc',
    '^rust_begin_unwind',
    '^rust_fuzzer_test_input',
    '^rust_oom',
    '^rust_panic',
    '^scanf',
    '^show_stack',
    '^core::panic',
    '^std::__terminate',
    '^std::io::Write::write_fmt',
    '^std::panic',
    '^std::process::abort',
    '^std::sys::unix::abort',
    '^std::sys::backtrace',
    '^std::sys_common::backtrace',
    '^__rust_start_panic',
    '^__scrt_common_main_seh',
    '^libgcc_s.so.*',
    '.*ASAN_OnSIGSEGV',
    '.*BaseThreadInitThunk',
    '.*DebugBreak',
    '.*DefaultDcheckHandler',
    '.*ForceCrashOnSigAbort',
    '.*MemoryProtection::CMemoryProtector',
    '.*PartitionAlloc',
    '.*RtlFreeHeap',
    '.*RtlInitializeExceptionChain',
    '.*RtlReportCriticalFailure',
    '.*RtlUserThreadStart',
    '.*RtlpHeapHandleError',
    '.*RtlpLogHeapFailure',
    '.*SkDebugf',
    '.*StackDumpSignalHandler',
    '.*__android_log_assert',
    '.*__tmainCRTStartup',
    '.*_asan_rtl_',
    '.*agent::asan::',
    '.*allocator_shim',
    '.*asan_Heap',
    '.*asan_check_access',
    '.*asan_osx_dynamic\\.dylib',
    '.*assert',
    '.*base::FuzzedDataProvider',
    '.*base::allocator',
    '.*base::android::CheckException',
    '.*base::debug::BreakDebugger',
    '.*base::debug::CollectStackTrace',
    '.*base::debug::StackTrace::StackTrace',
    '.*ieee754\\-',
    '.*libpthread',
    '.*logger',
    '.*logging::CheckError',
    '.*logging::.*LogMessage',
    '.*logging::.*NoreturnError',
    '.*stdext::exception::what',
    '.*v8::base::OS::Abort',
    '.*Runtime_AbortCSADcheck',
    '.* base/callback',
    '.* /rust(|c)/',
    '.*/AOSP\\-toolchain/',
    '.*/bindings/ToV8\\.h',
    '.*/crosstool/',
    '.*/gcc/',
    '.*/glibc\\-',
    '.*/googletest/',
    '.*/jemalloc/',
    '.*/libc\\+\\+',
    '.*/libc/',
    '.*/llvm\\-build/',
    '.*/minkernel/crts/',
    '.*/sanitizer_common/',
    '.*/tcmalloc/',
    '.*/vc/include/',
    '.*/vctools/crt/',
    '.*/win_toolchain/',
    '.*libc\\+\\+/',
    'c:/clusterfuzz/bot/build',
    '.*third_party/fuzztest/',
    '.*/memorycmp\\.c',
    '.*\\+Unknown',
    '.*<unknown module>',
    '.*Inline Function @',
    '^<unknown>$',
    '^\\[vdso\\]$',
    '^linux-gate.so.*$',
    '^panic$',
    '^runtime\\.',
    '^CrashTrampolineAsm',
    '^libc_io_functions_not_implemented_use_fdio_instead',
    '^<libclang_rt.asan.so>',
    '^__zx_panic',
    '^syslog::LogMessage',
    '^print_address_description',
    '^_etext',
    '^_swift_stdlib_',
    '.*centipede::',
    '.*fuzztest::internal::',
    '^V8_Fatal',
    '^blink::ReportV8FatalError',
    '^v8::api_internal::ToLocalEmpty',
    '^v8::internal::Isolate::PushStackTraceAndDie',
    '^v8::internal::Isolate::PushParamsAndDie',
    '^absl::log_internal::',
    '^SkAbort_FileLine',
    '^SkMutex::~SkMutex',
)


CLUSTERFUZZ_FUNCTION_IGNORE_REGEXES_IF_SYMBOLIZED = (
    '.*libc\\.so',
    '.*libc\\+\\+\\.so',
    '.*libc\\+\\+_shared\\.so',
    '.*libstdc\\+\\+\\.so',
    '.*libc-.*\\.so',
)


CASR_CPP_FUNCTION_IGNORE_REGEXES = (
    '^abort$',
    '^exit$',
    '^pthread_create$',
    '^pthread_kill$',
    '^raise$',
    '^tgkill$',
    '^__chk_fail$',
    '^__fortify_fail$',
    '^(|__)aeabi_',
    '^(|__)memcmp',
    '^(|__)memcpy',
    '^(|__)memmove',
    '^(|__)memset',
    '^(|__)strcmp',
    '^(|__)strcpy',
    '^(|__)strdup',
    '^(|__)strlen',
    '^(|__)strncpy',
    '^<null>',
    '^Abort\\(',
    '^CFCrash',
    '^ExitCallback',
    '^IsSandboxedProcess',
    '^MSanAtExitWrapper',
    '^New',
    '^RaiseException',
    '^SbSystemBreakIntoDebugger',
    '^SignalAction',
    '^SignalHandler',
    '^TestOneProtoInput',
    '^WTF::',
    '^WTFCrash',
    '^X11Error',
    '^_L_unlock_',
    '^__GI_',
    '^__asan::',
    '^__asan_',
    '^__assert_',
    '^__cxa_atexit',
    '^__cxa_rethrow',
    '^__cxa_throw',
    '^throw_exception',
    '^__dump_stack',
    '^__hwasan::',
    '^__hwasan_',
    '^__interceptor_',
    '^__kasan_',
    '^__libc_',
    '^__lsan::',
    '^__lsan_',
    '^__msan::',
    '^__msan_',
    '^__pthread_kill',
    '^__run_exit_handlers',
    '^__rust_try',
    '^__sanitizer::',
    '^__sanitizer_',
    '^__tsan::',
    '^__tsan_',
    '^__ubsan::',
    '^__ubsan_',
    '^_asan_',
    '^_hwasan_',
    '^_lsan_',
    '^_msan_',
    '^_objc_terminate',
    '^_sanitizer_',
    '^_start',
    '^__libc_start_main',
    '^_tsan_',
    '^_ubsan_',
    '^abort',
    '^alloc::',
    '^android\\.app\\.ActivityManagerProxy\\.',
    '^android\\.os\\.Parcel\\.',
    '^art::Thread::CreateNativeThread',
    '^asan_',
    '^asan\\.module_ctor',
    '^asan\\.module_dtor',
    '^calloc',
    '^check_memory_region',
    '^common_exit',
    '^delete',
    '^demangling_terminate_handler',
    '^bt_terminate_handler',
    '^dump_backtrace',
    '^dump_stack',
    '^exit_or_terminate_process',
    '^fpehandler\\(',
    '^free',
    '^g_log',
    '^generic_cpp_',
    '^gsignal',
    '^kasan_',
    '^fuzzer::',
    '^libfuzzer_sys::initialize',
    '^malloc',
    '^mozalloc_',
    '^new',
    '^object_err',
    '^operator',
    '^print_trailer',
    '^realloc',
    '^report_failure',
    '^scanf',
    '^show_stack',
    '^std::__terminate',
    '^std::terminate',
    '^std::sys::unix::abort',
    '^std::sys_common::backtrace',
    '^__scrt_common_main_seh',
    '.*ASAN_OnSIGSEGV',
    '.*BaseThreadInitThunk',
    '.*DebugBreak',
    '.*DefaultDcheckHandler',
    '.*ForceCrashOnSigAbort',
    '.*MemoryProtection::CMemoryProtector',
    '.*PartitionAlloc',
    '.*RtlFreeHeap',
    '.*RtlInitializeExceptionChain',
    '.*RtlReportCriticalFailure',
    '.*RtlUserThreadStart',
    '.*RtlpHeapHandleError',
    '.*RtlpLogHeapFailure',
    '.*SkDebugf',
    '.*StackDumpSignalHandler',
    '.*__android_log_assert',
    '.*__tmainCRTStartup',
    '.*_asan_rtl_',
    '.*agent::asan::',
    '.*allocator_shim',
    '.*asan_Heap',
    '.*asan_check_access',
    '.*asan_osx_dynamic\\.dylib',
    '.*assert',
    '.*base::FuzzedDataProvider',
    '.*base::allocator',
    '.*base::android::CheckException',
    '.*base::debug::BreakDebugger',
    '.*base::debug::CollectStackTrace',
    '.*base::debug::StackTrace::StackTrace',
    '.*ieee754\\-',
    '.*libpthread',
    '.*logger',
    '.*logging::CheckError',
    '.*logging::ErrnoLogMessage',
    '.*logging::LogMessage',
    '.*stdext::exception::what',
    '.*v8::base::OS::Abort',
    '.*pybind',
    '^PyCFunction',
    '^PyObject',
    '^PyEval',
    '^PyRun',
    '^Py_',
    '^atheris::',
)


CASR_CPP_FILEPATH_IGNORE_REGEXES = (
    '.*/usr/include/c\\+\\+/',
    '.*\\-gnu/c\\+\\+/',
    '.*\\-gnu/bits/',
    '.*/clang/',
    '.*base/callback',
    '.*/AOSP\\-toolchain/',
    '.*/bindings/ToV8\\.h',
    '.*/crosstool/',
    '.*/gcc/',
    '.*sysdeps/',
    '.*/glibc\\-',
    '.*/jemalloc/',
    '.*/libc\\+\\+',
    '.*/libc/',
    '.*/llvm\\-build/',
    '.*/minkernel/crts/',
    '.*/sanitizer_common/',
    '.*/tcmalloc/',
    '.*/vc/include/',
    '.*/vctools/crt/',
    '.*/win_toolchain/',
    '.*libc\\+\\+/',
    '.*/cxxsupp/',
    '.*/util/generic/',
    '.*/compiler\\-rt/lib/',
    '.*/libfuzzer/lib/',
    '.*/clang.*\\-rt/lib/',
    '.*\\+Unknown',
    '.*<unknown module>',
    '.*Inline Function @',
    '^<unknown>$',
    '^\\[vdso\\]$',
    '^linux-vdso.so.*$',
    '^linux-gate.so.*$',
    '.*libc\\.so',
    '.*libc\\+\\+\\.so',
    '.*libc\\+\\+_shared\\.so',
    '.*libstdc\\+\\+\\.so',
    '.*libc-.*\\.so',
    '.*libpthread\\.so',
    '.*libasan\\.so',
    '.*libubsan\\.so',
    '.*asan_with_fuzzer\\.so',
)


EXTRA_FUNCTION_IGNORE_REGEXES = (
    '^_Unwind_',
    '^std::__1?::',
    '^__pthread_',
    '^clone$',
)


ALL_FUNCTION_IGNORE_REGEXES = (
    CLUSTERFUZZ_FUNCTION_IGNORE_REGEXES
    + CLUSTERFUZZ_FUNCTION_IGNORE_REGEXES_IF_SYMBOLIZED
    + CASR_CPP_FUNCTION_IGNORE_REGEXES
    + EXTRA_FUNCTION_IGNORE_REGEXES
)

ALL_FILEPATH_IGNORE_REGEXES = CASR_CPP_FILEPATH_IGNORE_REGEXES

_COMPILED_FUNCTION_PATTERNS = tuple(
    re.compile(pattern) for pattern in dict.fromkeys(ALL_FUNCTION_IGNORE_REGEXES)
)
_COMPILED_FILEPATH_PATTERNS = tuple(
    re.compile(pattern) for pattern in dict.fromkeys(ALL_FILEPATH_IGNORE_REGEXES)
)


def is_vendored_noise_function(func_name):
    if not func_name:
        return False
    return any(pattern.match(func_name) for pattern in _COMPILED_FUNCTION_PATTERNS)


def is_vendored_noise_filepath(file_path):
    if not file_path:
        return False
    return any(pattern.match(file_path) for pattern in _COMPILED_FILEPATH_PATTERNS)
